[package]
name = "twt"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
csv = "1.2.0"
chrono = "0.4.23"
dirs = "4.0"
duration-string = "0.3"
xcb = { version = "1.2.0", features = ["screensaver"] }
